// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcAO28CUzpwzWIIESL3onZ2qFUg7pXTNU',
    appId: '1:697565458559:android:5480c4462ddb53e8bb4f4a',
    messagingSenderId: '697565458559',
    projectId: 'tourix-f476f',
    storageBucket: 'tourix-f476f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVtCsitUX-9LfQGZdO8UobHVeb2rCuRj8',
    appId: '1:697565458559:ios:49ace501fdfd2e09bb4f4a',
    messagingSenderId: '697565458559',
    projectId: 'tourix-f476f',
    storageBucket: 'tourix-f476f.firebasestorage.app',
    iosBundleId: 'com.example.tourix',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD461r3w3W94YFDhtw7m63dWoEi3ll8Gyg',
    appId: '1:697565458559:web:112673e621ae910bbb4f4a',
    messagingSenderId: '697565458559',
    projectId: 'tourix-f476f',
    authDomain: 'tourix-f476f.firebaseapp.com',
    storageBucket: 'tourix-f476f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVtCsitUX-9LfQGZdO8UobHVeb2rCuRj8',
    appId: '1:697565458559:ios:49ace501fdfd2e09bb4f4a',
    messagingSenderId: '697565458559',
    projectId: 'tourix-f476f',
    storageBucket: 'tourix-f476f.firebasestorage.app',
    iosBundleId: 'com.example.tourix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD461r3w3W94YFDhtw7m63dWoEi3ll8Gyg',
    appId: '1:697565458559:web:aace25e483e434dabb4f4a',
    messagingSenderId: '697565458559',
    projectId: 'tourix-f476f',
    authDomain: 'tourix-f476f.firebaseapp.com',
    storageBucket: 'tourix-f476f.firebasestorage.app',
  );

}